# Generated by Django 3.0.3 on 2020-03-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtype', models.CharField(choices=[('1', 'red'), ('2', 'yellow'), ('3', 'green'), ('4', 'blue'), ('5', 'gray')], default='5', max_length=1)),
                ('name', models.CharField(default='NoName Bed', max_length=20)),
                ('imgstatus', models.ImageField(blank=True, null=True, upload_to='bedsstatus')),
                ('imganalyze', models.ImageField(blank=True, null=True, upload_to='bedsanalyze')),
                ('suggestions', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shift', models.CharField(choices=[('D', 'Day'), ('N', 'Night'), ('LN', 'Late Night')], max_length=2)),
                ('personalid', models.IntegerField(unique=True)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='profileimg')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('history', models.CharField(default=None, max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('transcription', models.CharField(max_length=1000, null=True)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('age', models.SmallIntegerField()),
                ('statustype', models.CharField(choices=[('1', 'red'), ('2', 'yellow'), ('3', 'green')], max_length=1)),
                ('generalstatus', models.CharField(max_length=1000, null=True)),
                ('patientimg', models.ImageField(blank=True, null=True, upload_to='patientimg')),
                ('risks', models.CharField(max_length=500, null=True)),
                ('alerts', models.CharField(max_length=500, null=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=40)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtype', models.CharField(choices=[('1', 'red'), ('2', 'yellow'), ('3', 'green'), ('4', 'blue'), ('5', 'gray')], max_length=1)),
                ('send', models.DateTimeField()),
                ('done', models.DateTimeField(default=None, null=True)),
                ('msg', models.CharField(max_length=1000)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Bed_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterdate', models.DateField()),
                ('exitdate', models.DateField()),
                ('sickness', models.CharField(max_length=30)),
                ('bed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.Bed')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Nurse')),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='Patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Patient'),
        ),
        migrations.AddField(
            model_name='bed',
            name='nurse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Nurse'),
        ),
    ]
