# Generated by Django 3.0.4 on 2020-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20200306_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Nurse'),
        ),
    ]
