# Generated by Django 3.0.4 on 2020-03-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20200310_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nurse',
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Patient'),
        ),
    ]
