# Generated by Django 3.0.4 on 2020-03-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20200310_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.Bed'),
        ),
    ]
