# Generated by Django 3.0.4 on 2020-03-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_notifications_bed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedtype',
            field=models.CharField(choices=[('1', 'red'), ('2', 'yellow'), ('3', 'green')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='bed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='models.Bed'),
        ),
    ]
