# Generated by Django 3.0.4 on 2020-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20200311_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='done',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='send',
        ),
        migrations.AddField(
            model_name='notifications',
            name='donedate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='donetime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='senddate',
            field=models.DateField(default='2020-02-05'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sendtime',
            field=models.TimeField(default='11:30'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='statustype',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'yellow'), (3, 'green')], default=3),
        ),
        migrations.AlterField(
            model_name='bed_history',
            name='exitdate',
            field=models.DateField(null=True),
        ),
    ]
